[package]
name = "candela"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better-panic = "0.3.0"
bevy = "0.11"
bytemuck = "1.13.1"
lazy_static = "1.4.0"
# bevy_compute_buffers_helper = "0.1.2"
